name: Test django-formset

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        django-version: ["4.0.*", "4.1.*"]
        node-version: ["16.x"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        npm install --include=dev
        python -m pip install --upgrade pip
        python -m pip install "Django==${{ matrix.django-version }}"
        python -m pip install -r testapp/requirements.txt
        playwright install
    - name: Build Parser
      run: |
        npm run tag-attributes
    - name: Build Client
      run: |
        npm run esbuild
        npm run compilescss
    - name: Test with pytest
      run: |
        python -m pytest testapp
